run:
  go: '1.22'

linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - forbidigo
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - godot
  - err113
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - ireturn
  - loggercheck
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tenv
  - testableexamples
  - testifylint
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  - zerologlint
  - canonicalheader
  - copyloopvar
  - fatcontext
  - iface
  - intrange
  - mirror
  - recvcheck
  disable:
  - cyclop
  - depguard
  - dupl
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gocyclo
  - godox
  - mnd
  - gomoddirectives
  - lll
  - maintidx
  - musttag
  - nlreturn
  - nonamedreturns
  - paralleltest
  - tagliatelle
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-nmea)
  gofumpt:
    extra-rules: true
    module-path: github.com/twpayne/go-nmea
  goimports:
    local-prefixes: github.com/twpayne/go-nmea
  govet:
    disable:
    - fieldalignment
    - shadow
    enable-all: true
  ireturn:
    allow:
    - anon
    - empty
    - error
    - github\.com/twpayne/go-nmea\.Address
    - github\.com/twpayne/go-nmea\.Sentence
    - github\.com/twpayne/go-nmea/gps\.Address
    - github\.com/twpayne/go-nmea/ublox\.Address
    - stdlib
  misspell:
    locale: US
  stylecheck:
    checks:
    - all

issues:
  include:
  - EXC0011 # include issues about comments from `stylecheck`
  exclude-rules:
  - linters:
    - err113
    text: do not define dynamic errors, use wrapped static errors instead
  - linters:
    - forbidigo
    path: ^cmd/
  - linters:
    - inamedparam
    path: _test\.go$
